### ISSUE TITLE
Using the Downloadable Code

### ISSUE THREAD

**Issue by UchihaKite** [PacktPublishing/Mastering-SFML-Game-Development#1]
Good Afternoon,
So, I purchased this book because it seemed to have a lot of topics that I have been really interested in learning about. However, upon buying the book, I noticed that the Code I Downloaded is not already set up in a Visual Studios Project. So, I have been trying for about an hour now to set it up, with no success. I tried including the Shared Code folder as an additional include directory, however, I get the "../../Debug/DebugOverlay.h" doesn't exist error. Could someone please just tell me how to create a new project and include all the files into it? I just want to see the Chapter 2 project, and play around with it so I can actually learn.

**Comment by sschellhoff** [comment]
You are not the only one. I started with the code of chapter two and made a CMAKE file to generate a makefile in my case. But you can use CMAKE for Visual Studio Solutions too. The real problem is that there are lot's of bugs in the code. I resolved the problems my compiler found. Currently i get segmentation faults when i try to run the executable for chapter 2. I try to debug and fix the code but it isn't fun to do that. Maybe we should make a new repository with the code and fix it with multiple people. I also wrote the author in the SFML forum. You can check the post here: [https://en.sfml-dev.org/forums/index.php?topic=23877.msg162474](https://en.sfml-dev.org/forums/index.php?topic=23877.msg162474)

**Comment by techsachinkumar** [comment]
Hi @sschellhoff 

These are the final codes provided to us by the author. 
I have seen your post on the forum and also your code updates.
You can provide us with a pull merge request for the updated codes so as to we can check and make the necessary changes on approval.

Regards
